### ISSUE TITLE
RPC documentation

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/web3_proxy#133]
The RPC doc in the manual just says ` Coming soon...`:
![Screenshot 2023-06-13 at 13 57 39](https://github.com/threefoldtech/web3_proxy/assets/3511318/e128e303-775a-451e-a98c-16db287e661d)

The readme [states](https://github.com/threefoldtech/web3_proxy#documentation) that OpenRPC json files are  generated in the documentation but a single json file for all clients is not very human readable and  `https://threefoldtech.github.io/web3_proxy/openrpc/<client_name>/openrpc.json` requires knowledge of the client name and is again not human readable.

The openrpc playground could be a solution  but the link in the readme opens an OpenRPC playground with the default petstore example:
![Screenshot 2023-06-14 at 08 13 31](https://github.com/threefoldtech/web3_proxy/assets/3511318/b694c4eb-3ea6-4a87-a98a-768238fc30e5)

**Comment by timurgordon** [comment]
#133 is a minor fix by adding the links to the playgrounds of each client, do you think it's necessary to have separate pages for each under the rpc chapter @robvanmieghem? It might be a bit redundant
