### ISSUE TITLE
port https://github.com/threefoldtech/vgrid to 3bot

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/web3_proxy#179]
https://github.com/threefoldtech/vgrid

## REQUIREMENTS

- find nodes based on all kinds of parameters
- query ZOS for stats
- examples work
- make mdbook as tutorial

**Comment by sameh-farouk** [comment]
**Update:** 
- [x] find nodes based on all kinds of parameters (vGrid filters updated based on latest params available on gridproxy )
- [x] query ZOS for stats (Added `get_node_stats_by_id` to query gridproxy `/nodes/{ID}/statistics/` endpoint and add relevant models)
- [x] examples work (All examples fixed now)
- [X] make mdbook as tutorial

**PR**: #180
**PR**: #186 
**PR**: #191

**Comment by sameh-farouk** [comment]
**Update**: PRs Waiting for review
