### ISSUE TITLE
build_test workflow fails

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/web3_proxy#185]

**Comment by alichaddad** [comment]
This [file](https://github.com/threefoldtech/3bot/blob/development_pipeline/web3gw/examples/eth/deploy_vm_with_eth.v) is one of the issues causing the pipeline to fail and I am not sure if it us still needed or not. A lot of the functions used here no longer exist.
@robvanmieghem

**Comment by robvanmieghem** [comment]
@brandonpille Can you check this?

**Comment by brandonpille** [comment]
> 

Which functions no longer exist? Because this was a nice example to be able to deploy a VM using only ethereum. Not even needing to have lumens for doing the bridging.

**Comment by alichaddad** [comment]
The functions causing the errors here: https://github.com/threefoldtech/3bot/actions/runs/5939365470/job/16105602665

**Comment by brandonpille** [comment]
Most of these functions have been renamed and or modified a little bit. Please DM me if you can't find which function has been renamed to what, I'll help you.

**Comment by alichaddad** [comment]
Fixed as of this https://github.com/threefoldtech/3bot/commit/c68f99b1f83a7ca5b5fecf1f41dfb157dd9f792e
