### ISSUE TITLE
3lang examples and howto

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/web3_proxy#193]
There is some documentation on 3lang in the manual ( which still needs to be added in the navigation structure: #189 ).
From this doc it's impossible to get started, adding some examples for tfgrid actions with a small how to get it working would be very useful.

**Comment by robvanmieghem** [comment]
Just noticed there are examples at `web3gw/examples/threelang`.  I would move them to the manual.

**Comment by robvanmieghem** [comment]
Moved the threelang examples to the manual: 6554705e94dd67dd303c429132477e1a78c74393

**Comment by robvanmieghem** [comment]
and fixed the links: #195

**Comment by ashraffouda** [comment]
only managed to parse the 3lang md file but the runners are broken trying to fix it but there is a stuff removed which we depend on like explorer, created an issue for it https://github.com/threefoldtech/3bot/issues/201

**Comment by ashraffouda** [comment]
the explorer part is kinda merged to tfgrid and so far, I'm still fixing the clients so we have working examples afterwards

**Comment by ashraffouda** [comment]
some clients are fixed, vm client is somehow broken, there is an issue to track this https://github.com/threefoldtech/3bot/issues/202
