### ISSUE TITLE
explorer module doesn't exist/removed

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/web3_proxy#201]
for example in tfgrid client there is a dependency on explorer module
https://github.com/threefoldtech/3bot/blob/development_integration/web3gw/client/threelang/tfgrid/handler.v#L4
this module is used to get nodes, farms .... 
not sure what is the intention of removing it, should we return it back? or what?

**Comment by alichaddad** [comment]
Explorer was merged to tfgrid client, see https://github.com/threefoldtech/3bot/commit/bb430a2f55e1dc9ef8193574f2beab45c59fb574.
