### ISSUE TITLE
fix vm client 

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/web3_proxy#202]
the current [vm](https://github.com/threefoldtech/3bot/blob/development_integration/web3gw/client/threelang/tfgrid/vm.v) client  is not aligned at all with the current server side implementation 
the methods in server side is not reflecting the correct implementation for [example](https://github.com/threefoldtech/3bot/blob/development_integration/web3gw/client/threelang/tfgrid/vm.v#L7)
in this line the machine name is different from the network name while in the code it expects to be the same as [here](https://github.com/threefoldtech/3bot/blob/development_integration/web3gw/client/threelang/tfgrid/vm.v#L40)
also the code expects to deploy many vms while in server side it is only deployes one vm 
so this needs to be fixed or refactored

**Comment by despiegk** [comment]
new story will be created which should also catch this
