### ISSUE TITLE
use grid-cli to create deployments insted of rpc 

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/web3_proxy#205]
as per discussion with @despiegk we will move to grid-cli instead of rpc to create deployments on the grid
- [x] use direct client instead of rmb-peer and redis
- [x] implement delete deployment
- [x] add metadata to deployment
- [x] implement wait on deployment until it is created
- [x] fix todos comments
- [x] use names in deployments, keep contract id internal so it is easy for the user to identify his deployments
- [x] list taken ports on node for wireguard
- [x] a small graphql client is needed to list contracts for the user and get deployment name(projectname) from it
- [x] rollback
- [x] update the examples
- [x] deploy network

**Comment by ashraffouda** [comment]
- working on chaging grid-cli to use direct client of rmb instead of using rmb-peer and redis is like 70% done, still needs to be continued
- grid cli deployer needs more functionality as now is not doing roll back if deployment is faild also removing updating deployments doesn't exist

**Comment by ashraffouda** [comment]
usage of direct rmb works for deployments 
deployer is now provide very basic functionality for doing deployments and getting the deployed stuff

**Comment by 0oM4R** [comment]
fixed some todo comments, 
WIP: get node taken ports

**Comment by 0oM4R** [comment]
done with get node taken ports, 
WIP : wireguard access

**Comment by 0oM4R** [comment]
Updates: 
- after some search we could'n create curve25519 public key, and libsodiom doesn't support it, i added comments that guide the user to create the keys using wireguard. 
- rollback is added to deploy function 
- updated the examples

**Comment by 0oM4R** [comment]
updates: 
- metadata is done
- added graphql to the client 
- get deployments by the project name
- use logger in deployer
