### ISSUE TITLE
can't build grid-cli (griddriver) & web3gw

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/web3_proxy#208]
```bash
go build
# github.com/threefoldtech/tfchain/clients/tfchain-client-go
../../../../../go/pkg/mod/github.com/threefoldtech/tfchain/clients/tfchain-client-go@v0.0.0-20231004130631-a920b0f5d3de/account.go:62:23: undefined: subkey.SS58Address
../../../../../go/pkg/mod/github.com/threefoldtech/tfchain/clients/tfchain-client-go@v0.0.0-20231004130631-a920b0f5d3de/account.go:68:25: undefined: subkey.SS58Address
../../../../../go/pkg/mod/github.com/threefoldtech/tfchain/clients/tfchain-client-go@v0.0.0-20231004130631-a920b0f5d3de/account.go:91:16: undefined: subkey.SS58Address
../../../../../go/pkg/mod/github.com/threefoldtech/tfchain/clients/tfchain-client-go@v0.0.0-20231004130631-a920b0f5d3de/account.go:103:22: assignment mismatch: 2 variables but kyr.SS58Address returns 1 value
../../../../../go/pkg/mod/github.com/threefoldtech/tfchain/clients/tfchain-client-go@v0.0.0-20231004130631-a920b0f5d3de/account.go:103:38: cannot use network (variable of type uint8) as uint16 value in argume
```

**Comment by despiegk** [comment]
i have renamed it to griddriver, because its not really a usable grid-cli, its too low level for it

**Comment by despiegk** [comment]
check build instructions

**Comment by despiegk** [comment]
make sure .gitignore is ok

**Comment by 0oM4R** [comment]
- [x] fixed griddriver build at [fix go-subkey version](https://github.com/threefoldtech/3bot/commit/c3e24b6d64a7b1c065b13d508723458d6c721c1e)
- [x] fixed web3gw build at [fix deps versions](https://github.com/threefoldtech/3bot/commit/5c215df326524993f131d9b32bd91ec9edc95a8c)
- [x] update gitignore
- [x] update build instructions

**Comment by 0oM4R** [comment]
> * [x]  fixed griddriver build at [fix go-subkey version](https://github.com/threefoldtech/3bot/commit/c3e24b6d64a7b1c065b13d508723458d6c721c1e)
> * [x]  fixed web3gw build at [fix deps versions](https://github.com/threefoldtech/3bot/commit/5c215df326524993f131d9b32bd91ec9edc95a8c)


Keep in mind that running the `update.sh` file could cause dependencies to break and the build to fail. This is because the `go get -u` command upgrades packages to the latest available version without considering whether or not that version is compatible.
