### ISSUE TITLE
documentation is not clear enough

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/web3_proxy#41]
documentation is not clear enough to explain the purpose of the web3proxy and after following the documentation it does not build correctly.
![image](https://user-images.githubusercontent.com/110984055/235858679-36003587-c4d7-4ae5-bc1e-9ded726a595c.png)

**Comment by khaledyoussef24** [comment]
back end side documented now and built with success but there are 7 examples on the web3proxy but there is no clear documentation for every example and how to use every call
![image](https://github.com/threefoldtech/web3_proxy/assets/110984055/cc32954e-6bf1-4a2e-b932-746e87488673)

**Comment by DylanVerstraete** [comment]
Updated the manual with clear example documentation. @khaledyoussef24 can you please check and let me know if it's more clear now? See https://threefoldtech.github.io/web3_proxy/index.html
