### ISSUE TITLE
Ethereum bridge client

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/web3_proxy#51]
both directions

Needs V client + example scripts

**Comment by DylanVerstraete** [comment]
Added in https://github.com/threefoldtech/web3_proxy/tree/development/examples/eth

**Comment by robvanmieghem** [comment]
Verified it on production and it works great.
There is some naming inconsistency though, in the Stellar v client the function is called `bridge_to_eth` and in the Ethereum v client it is called `withdraw_eth_tft_to_stellar`.

The same for the server and rpc methods ( which are not documented btw).

My personal preference goes to `bridge_to_...`

**Comment by DylanVerstraete** [comment]
resolved in https://github.com/threefoldtech/web3_proxy/commit/0965489c6835f15dc3d8cc1e628edf26c2ba82fe
