### ISSUE TITLE
add docs for sftpgo subcommand and sal

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/web3_proxy#83]
should live in the manual directory

**Comment by alichaddad** [comment]
Done as part of #78

**Comment by ashraffouda** [comment]
done as a part of https://github.com/threefoldtech/web3_proxy/pull/72/files

**Comment by DylanVerstraete** [comment]
done: https://threefoldtech.github.io/web3_proxy/examples/sftpgo/examples.html
