### ISSUE TITLE
3lang: Tfgrid: define 3lang language for Tfgrid and implement parsing

### ISSUE THREAD

**Issue by brandonpille** [threefoldtech/web3_proxy#94]
3lang is a language that the users can use to tell the web3_proxy what calls to execute. It should be very user friendly and easy to write. It is based on markdown syntax. Look at [this issue](https://github.com/threefoldtech/home/issues/1434) to see an example. 

With this issue we want to define the language for all functionality from the tfgrid client:

- [x] Translate all possible/logical calls from V library (only tfgrid client) to [actions from markdowndocs](https://github.com/freeflowuniverse/crystallib/tree/development/markdowndocs)
- [x] Prepare example of markdown files that show us how the user would do specific things (deploy vms, etc)
- [x] Let @brandonpille review before Kristof can review
- [x] Implement the parsing part

**Comment by robvanmieghem** [comment]
I was going through the examples and the manual. The network given in the vm creation is unclear to me. In the examples  and the manual `skynet` is used but should this be an already created network, is it created  and if so, what is the scope?

**Comment by robvanmieghem** [comment]
Is there a good reason why vm actions are `!!tfgrid.machines` while the example in the story mentioned above uses `!!tfgrid.vm` ?

**Comment by despiegk** [comment]
please walk over with me to check

- syntax
- documentation
- example scripts
- functionality

we will make issues for missing or not good enough items

**Comment by despiegk** [comment]
please walk over with me to check

- syntax
- documentation
- example scripts
- functionality

we will make issues for missing or not good enough items

**Comment by despiegk** [comment]
lets close this one for now, and replace by a new one

**Comment by despiegk** [comment]
see new one
